sudo: required
service: 
  - docker

before_install:
 - docker build -t anuraagmoturi/client-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run anuraagmoturi/client-tests npm run test -- --coverage

after_success:
  - docker build -t anuraagmoturi/multi-client ./client
  - docker build -t anuraagmoturi/multi-nginx ./nginx
  - docker build -t anuraagmoturi/multi-server ./server
  - docker build -t anuraagmoturi/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push anuraagmoturi/multi-client
  - docker push anuraagmoturi/multi-nginx
  - docker push anuraagmoturi/multi-server
  - docker push anuraagmoturi/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-multicontainer
  env: DockerMulticontainer-env
  bucket_name: elasticbeanstalk-us-east-2-381039485210
  bucket_path: docker-multicontainer
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
  secure: $AWS_SECRET_KEY
  